package blogviewerdata;

import elements.User;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author leonardo
 */
public class ViewUser extends javax.swing.JFrame {

    public User user;
    public BlogViewerData venIni;

    public ViewUser(User user, BlogViewerData venIni) {
        initComponents();
        this.venIni=venIni;
        this.user = user;
        
        this.name.setText(user.name);
        this.username.setText(user.username);
        this.website.setText(user.website);
        this.phone.setText(user.phone);
        this.email.setText(user.email);
        this.id.setText(user.id+"");
        
        if(user.company!=null){
            this.namec.setText(user.getCompanyName());
            this.cp.setText(user.getCompanyCatchPhrase());
            this.bs.setText(user.getCompanyBs());
        }
        if(user.address!=null){
            this.street.setText(user.getAddressStreet());
            this.suite.setText(user.getAddressSuite());
            this.city.setText(user.getAddressCity());
            this.zipcode.setText(user.getAddressZipcode());
            if(user.address.geo!=null){
                this.lat.setText(user.address.geo.lat);
                this.lon.setText(user.address.geo.lng);
            }
        }
        /*panel=new javax.swing.JPanel(){
            @Override
            public void paint(Graphics g){
                super.paint(g);
                setBackground(new Color(90,155,191));
                g.drawImage(Apoyo.user, 20, 20, 120, 140, null);
            }
        };*/
        //scroll.setViewportView(panel);
        panel.setPreferredSize(new java.awt.Dimension(170, 140));
        
        //this.getContentPane().setBackground(new Color(204,204,204));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        panel.requestFocus();
    }

    private ViewUser() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel(){

            @Override
            public void paint(Graphics g){
                //super.paint(g);
                g.drawImage(Apoyo.fondo, 0, 0,getWidth(),getHeight(), this);
                paintComponents(g);
            }

        };
        jPanel1 = new javax.swing.JPanel(){

            @Override
            public void paint(Graphics g){
                super.paintComponent(g);
                paintComponents(g);
            }

        };
        cp = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namec = new javax.swing.JLabel();
        bs = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel(){

            @Override
            public void paint(Graphics g){
                super.paintComponent(g);
                paintComponents(g);
            }

        };
        suite = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        street = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lat = new javax.swing.JLabel();
        zipcode = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lon = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel(){

            @Override
            public void paint(Graphics g){
                super.paintComponent(g);
                paintComponents(g);
            }

        };
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        website = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel(){
            @Override
            public void paint(Graphics g){
                g.drawImage(Apoyo.user, 20, 20, 120, 140, null);
            }
        };
        jPanel5 = new javax.swing.JPanel(){

            @Override
            public void paint(Graphics g){
                super.paintComponent(g);
                paintComponents(g);
            }

        };
        botonPosts = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        botonComments = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel4.setBackground(new java.awt.Color(90, 155, 191));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cp.setBackground(new java.awt.Color(51, 0, 255));
        cp.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        cp.setForeground(new java.awt.Color(140, 140, 140));
        cp.setText("catchPhrase");
        jPanel1.add(cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 90, 420, 32));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Compañía");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        namec.setBackground(new java.awt.Color(51, 0, 255));
        namec.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        namec.setForeground(new java.awt.Color(140, 140, 140));
        namec.setText("namec");
        jPanel1.add(namec, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 49, 420, 32));

        bs.setBackground(new java.awt.Color(51, 0, 255));
        bs.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        bs.setForeground(new java.awt.Color(140, 140, 140));
        bs.setText("bs");
        jPanel1.add(bs, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 134, 420, 32));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("CP");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 96, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Nombre");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 55, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("bs");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 530, 180));

        jPanel2.setBackground(new java.awt.Color(243, 243, 243));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        suite.setBackground(new java.awt.Color(51, 0, 255));
        suite.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        suite.setForeground(new java.awt.Color(140, 140, 140));
        suite.setText("suite");
        jPanel2.add(suite, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 85, 280, 32));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Dirección");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        street.setBackground(new java.awt.Color(51, 0, 255));
        street.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        street.setForeground(new java.awt.Color(140, 140, 140));
        street.setText("street");
        jPanel2.add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 45, 280, 32));

        city.setBackground(new java.awt.Color(51, 0, 255));
        city.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        city.setForeground(new java.awt.Color(140, 140, 140));
        city.setText("city");
        jPanel2.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 125, 280, 32));

        jLabel12.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel12.setText("Suite");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel13.setText("Calle");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel14.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel14.setText("Ciudad");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        lat.setBackground(new java.awt.Color(51, 0, 255));
        lat.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        lat.setForeground(new java.awt.Color(140, 140, 140));
        lat.setText("lat");
        jPanel2.add(lat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 205, 280, 32));

        zipcode.setBackground(new java.awt.Color(51, 0, 255));
        zipcode.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        zipcode.setForeground(new java.awt.Color(140, 140, 140));
        zipcode.setText("zipcode");
        jPanel2.add(zipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 165, 280, 32));

        jLabel15.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel15.setText("Código postal");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel16.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel16.setText("Latitud");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        lon.setBackground(new java.awt.Color(51, 0, 255));
        lon.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        lon.setForeground(new java.awt.Color(140, 140, 140));
        lon.setText("lon");
        jPanel2.add(lon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 245, 280, 32));

        jLabel18.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel18.setText("Longitud");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 430, 290));

        jPanel3.setBackground(new java.awt.Color(243, 243, 243));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel4.setText("Email");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 133, -1, -1));

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 54, -1, -1));

        name.setBackground(new java.awt.Color(51, 0, 255));
        name.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(140, 140, 140));
        name.setText("name");
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 48, 320, 32));

        jLabel3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel3.setText("Nombre de usuario");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 93, -1, -1));

        username.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(140, 140, 140));
        username.setText("username");
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 86, 320, 32));

        email.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(140, 140, 140));
        email.setText("email");
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 127, 320, 32));

        jLabel5.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel5.setText("Sitio Web");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 203, -1, -1));

        website.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        website.setForeground(new java.awt.Color(140, 140, 140));
        website.setText("website");
        jPanel3.add(website, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 197, 320, 32));

        jLabel6.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel6.setText("Teléfono");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 242, -1, -1));

        phone.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(140, 140, 140));
        phone.setText("phone");
        jPanel3.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 236, 320, 32));

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Información Personal");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel20.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jLabel20.setText("Id");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        id.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        id.setForeground(new java.awt.Color(140, 140, 140));
        id.setText("id");
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 164, 320, 32));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 290));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Blog Viewer Data");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        panel.setBackground(new java.awt.Color(90, 155, 191));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        jPanel4.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 180, 180));

        jPanel5.setBackground(new java.awt.Color(243, 243, 243));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPosts.setBackground(new java.awt.Color(51, 51, 51));
        botonPosts.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        botonPosts.setForeground(new java.awt.Color(255, 255, 255));
        botonPosts.setText("Ver Posts");
        botonPosts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPostsActionPerformed(evt);
            }
        });
        jPanel5.add(botonPosts, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 50, -1, -1));

        jLabel19.setBackground(new java.awt.Color(51, 51, 51));
        jLabel19.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Actividad");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        botonComments.setBackground(new java.awt.Color(51, 51, 51));
        botonComments.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        botonComments.setForeground(new java.awt.Color(255, 255, 255));
        botonComments.setText("Ver Comentarios");
        botonComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCommentsActionPerformed(evt);
            }
        });
        jPanel5.add(botonComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 250, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPostsActionPerformed
        venIni.showPostsBy(user);
    }//GEN-LAST:event_botonPostsActionPerformed

    private void botonCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCommentsActionPerformed
        venIni.showCommentsBy(user);
    }//GEN-LAST:event_botonCommentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComments;
    private javax.swing.JButton botonPosts;
    private javax.swing.JLabel bs;
    private javax.swing.JLabel city;
    private javax.swing.JLabel cp;
    private javax.swing.JLabel email;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lat;
    private javax.swing.JLabel lon;
    private javax.swing.JLabel name;
    private javax.swing.JLabel namec;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel street;
    private javax.swing.JLabel suite;
    private javax.swing.JLabel username;
    private javax.swing.JLabel website;
    private javax.swing.JLabel zipcode;
    // End of variables declaration//GEN-END:variables
}
